
#scenario: see solve.py
#first argument must be #years
#20a counts back from 2020
#H2u or H2s: underground or steel tanks; nH2t without H2 turbine; wm with methanol

run: "230410-20a-UK-DE-bioco2"

run_settings:
  country: [UK,DE]
  scenario: [20a-H2s-wm-nH2t-mflex0-bioco2,20a-H2s-wm-nH2t-mflex20-bioco2,20a-H2s-wm-nH2t-mflex50-bioco2]

current_version: 190929

cutout_folder: "../cutouts/"

octant_folder: "../octants/"

weather_years: [2011,2012,2013,2014]

tech_years: [2020,2030,2040,2050]

tech_years_default: 2030

cost_year_assumptions: 2015
cost_year: 2020
inflation: 2



float_upper_limit: 1.e+7

tech_data_commit: "3a23cfc5808df00a2c039fd0e7ce8755a090d4df"
trace_commit: "55e71c86d36869079b46377ce7ef16a46afa1d99"


renewable:
  onwind:
    method: wind
    resource:
      turbine: Vestas_V112_3MW
  solar:
    method: pv
    resource:
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    correction_factor: 1.

#LHV
mwh_per_t:
  methanol: 5.54

#LHV at 20 C
mwh_per_m3:
  methanol: 4.4

octant_compression:
  complevel: 4
  least_significant_digit: 5


balances_to_display: ["electricity","hydrogen"]

preferred order: ["wind","solar","battery storage","battery inverter","hydrogen storage","hydrogen storing compressor","hydrogen electrolyser","seawater desalination","hydrogen turbine"]


solver:
  name: gurobi
  options: gurobi-default

solver_options:
  gurobi-default:
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    seed: 10              # Consistent seed for all plattforms


colors:
  wind : "#3B6182"
  solar: "#FFFF00"
  battery: "#999999"
  battery_charge: "#999999"
  battery_discharge: "#999999"
  battery discharger: "#999999"
  battery_power: "#999999"
  battery inverter: "#999999"
  battery_energy: "#666666"
  battery storage: "#666666"
  hydrogen_turbine: red
  hydrogen turbine: red
  hydrogen_electrolyser: cyan
  hydrogen electrolyser: cyan
  hydrogen_energy: magenta
  hydrogen storage: magenta
  hydrogen storing compressor: "#ff66ff"
  hydrogen_compressor: "#ff66ff"
  hydrogen storing decompressor: "#660066"
  lh2 shipping: green
  dispatchable1: orange
  dispatchable2: lime
  load: black
  hydrogen_load: purple
  dac: "#999966"
  co2 storage: "#666633"
  heat pump: red
  methanol synthesis: "#F08080"
  methanol storage: black
  Allam cycle: pink
