name: methanol-ldes
channels:
  - bioconda
  - gurobi
  - conda-forge
dependencies:
  - numpy
  - pandas
  - xarray
  - pypsa
  - snakemake
  - notebook
  - gurobi
  - seaborn
  - matplotlib
  - ipython
  - ipykernel
  - nbconvert
